# Generated by Django 4.2 on 2026-02-11 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecon', '0001_initial'),
        ('quizlet_copy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='quizlet_copy.flashcardset'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'mastered'], name='quizlet_cop_user_id_8e22e8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'confidence_level'], name='quizlet_cop_user_id_0048de_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'next_review_date'], name='quizlet_cop_user_id_c47ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['next_review_date', 'user'], name='quizlet_cop_next_re_65d961_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'times_studied'], name='quizlet_cop_user_id_649a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['flashcard', 'mastered'], name='quizlet_cop_flashca_941a48_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['last_studied'], name='quizlet_cop_last_st_023ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', '-last_studied'], name='quizlet_cop_user_id_d19389_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'flashcard')},
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['created_by', 'is_public', '-created_at'], name='quizlet_cop_created_06c469_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['is_public', '-created_at'], name='quizlet_cop_is_publ_0fe336_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['created_by', '-created_at'], name='quizlet_cop_created_8740a8_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['title', 'is_public'], name='quizlet_cop_title_i_3f7652_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['updated_at'], name='quizlet_cop_updated_0a051d_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['created_by', 'title'], name='quizlet_cop_created_cf7ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set', '-created_at'], name='quizlet_cop_flashca_744cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set'], name='quizlet_cop_flashca_40f2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['-created_at'], name='quizlet_cop_created_c611b6_idx'),
        ),
    ]
